files: ".*"
#exclude: "app/migrations/.*"
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: ["--py39-plus"]
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
        name: Reorder Python imports (src, tests)
        args: ["--application-directories", "app"]
  - repo: https://github.com/python/black
    rev: 22.12.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: "app/models/__init__.py"
        args: ["--max-line-length=120"]
        additional_dependencies:
          - flake8-bugbear
          - flake8-implicit-str-concat

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        exclude: ^tests/
        additional_dependencies: [pydantic, strawberry-graphql, types-requests, types-redis, types-python-dateutil, types-pytz] # add if use pydantic

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/python-poetry/poetry
    rev: 1.3.1
    hooks:
      - id: poetry-check
        files: pyproject.toml
      - id: poetry-lock
        args: ["--no-update"]
        files: pyproject.toml
      - id: poetry-export
        args:
          [
            "-f",
            "requirements.txt",
            "-o",
            "requirements/requirements.txt",
            "--without-hashes",
            "--without-urls",
          ]
        files: pyproject.toml
      - id: poetry-export
        args:
          [
            "-f",
            "requirements.txt",
            "-o",
            "requirements/dev_requirements.txt",
            "--without-hashes",
            "--without-urls",
            "--dev",
          ]
        files: pyproject.toml
